// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhnkzxagkwjhiidhejxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhobmt6eGFna3dqaGlpZGhlanhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMzM5MjUsImV4cCI6MjA3MDcwOTkyNX0.cTG7bsz_mTmQDFiI1XEp2-ci2MDKPKWyk0K7PEmbCP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});